# Generated by Django 2.2.7 on 2022-10-10 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_nsme', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('cretaed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=200)),
                ('account_number', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pay', to='users.User_details')),
            ],
        ),
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.TextField(max_length=250)),
                ('address_line2', models.TextField(max_length=250)),
                ('city', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('country', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_adr', to='users.User_details')),
            ],
        ),
    ]
